### ISSUE TITLE
Running laughter detector errors:

### ISSUE THREAD

**Issue by magrawala** [jrgillick/laughter-detection#1]
Ran into a couple of issues trying to run the laughter detector:

1) The latest version of librosa 0.6.1 doesn't run with the latest version of joblib 0.12.0. Had to rollback to joblib 0.11.0 for librosa to work.

2) laugh_segmenter.py is dependent on python_speech_features library. 

And two problems I haven't been able to solve:

1) I get this error when I run (though this is only a warning)

UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '

2) More importantly I get this error saving out the result:

Traceback (most recent call last):
  File "segment_laughter.py", line 50, in <module>
    laughs = laugh_segmenter.segment_laughs(input_path,model_path,output_path,threshold,min_length) 
  File "/Users/maneesh/development/testCode/jnotebooks/laughter-detection/laugh_segmenter.py", line 112, in segment_laughs
    librosa.output.write_wav(wav_path, (laughs * maxv).astype(np.int16), full_res_sr)
  File "/Users/maneesh/anaconda2/envs/tensorflow/lib/python2.7/site-packages/librosa/output.py", line 223, in write_wav
    util.valid_audio(y, mono=False)
  File "/Users/maneesh/anaconda2/envs/tensorflow/lib/python2.7/site-packages/librosa/util/utils.py", line 159, in valid_audio
    raise ParameterError('data must be floating-point')
librosa.util.exceptions.ParameterError: data must be floating-point

**Comment by jrgillick** [comment]
Sorry for the delay - thanks for letting me know!

- I fixed the python_speech_features dependency.
- I attempted a fix for the issue saving the output. If it still doesn't work, can you send me your audio file so that I can try to recreate it? I think it's something to do with the format of the input audio file.

**Comment by magrawala** [comment]
I should have written earlier. I got things to work by rolling back to librosa 0.5.0. Which version of that library are you on?

**Comment by jrgillick** [comment]
Ah ok cool. I'm on 0.5.0 as well. Glad you got it working!

**Comment by magrawala** [comment]
Let me know if you update for the latest librosa which I think is 0.6.1

**Comment by jrgillick** [comment]
It's working for me on librosa 0.6.1 after the change I just pushed. I did need to do what you said and rollback to joblib 0.11.0 in order to upgrade librosa.
