### ISSUE TITLE
False positives due to music (BGM)

### ISSUE THREAD

**Issue by ssv5088** [jrgillick/laughter-detection#3]
Hi Jon Gillick, 

I tried you code with some podcast audio files and it works excellent. There are some false positive outputs too, where I do see music ( BGM ) also are identified as laughter. 

https://content.production.cdn.art19.com/validation=1563883983,1e1020f2-6a03-565e-9c12-e427174fb512,IvBM_SoTXagDGbWmNuqWJkkjFQc/episodes/c3911ffa-4f63-4ceb-810a-c556380d4e24/31b642ca70a6683fab29cd9a11ba6fd448144f26c9491b13d685f2cb2af2bedd20d4e60a58b1a669366c25cd63ffdeb51a2ef07d68a4c02b828598fe765b54a9/MoS-Dara-V11-BP-Mix.mp3

Is there anyway, to detect music and remove them? Do you have any model file for music detection?

I am also interested in the Switchboard files and if possible logic to build my own model using laughter samples I have. 

Thank you very much in advance.

SSV

**Comment by jrgillick** [comment]
Hi SSV, 

Thanks for your comment. Unfortunately, the model posted here was only trained on Switchboard, so it's only really good at distinguishing laughter from speech - the code on this repo isn't set up to really easily plug in another dataset besides Switchboard, but you could do it if you're interested to dig into it a bit.

The good news is that I'm hoping to improve both of those issues sometime, hopefully in the next few months (reducing false positives and improving the training code). I can't promise when I'll get to it though.

In the meantime, if most of your false positives are coming from music, you might try looking at models for Music Segmentation. I haven't worked on that problem, but a quick Google search turned up this code: https://pypi.org/project/inaSpeechSegmenter/. Maybe something like that will help.

Jon

**Comment by jrgillick** [comment]
This should work somewhat better now that I've updated the library to Version 2
